[package]
name = "detection"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25.5", default-features = false, features = ["jpeg"] }
tract = "0.21.7"
tract-onnx = "0.21.7"
anyhow = "1.0.95"
